version: "3"
services:
  postgres:
    image: postgres:9.5-alpine
    # Uncomment to expose PostgreSQL to host
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=vagrant
  client:
    build:
      context: .
    environment:
      - POSTGRES_USER=vagrant
    volumes:
      - .:/data
    links:
      - postgres

